"""Positive control: verify the pipeline detects group symmetry when it exists.

Embeds exact S_3 representations in synthetic activations at various noise
levels and subspace dimensions, then runs the same operator fitting and
group relation tests used on real model activations.

This establishes:
1. The pipeline correctly identifies exact group structure (relation errors → 0)
2. How noise degrades detection (calibration curve)
3. That real model errors are far above what noisy group structure looks like

Usage:
    python scripts/positive_control.py
    python scripts/positive_control.py --noise-levels 0.0 0.05 0.1 0.2 0.5
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
from scipy.linalg import block_diag
from scipy.stats import ortho_group

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.datasets.permutations import Permutation, PermutationGroup
from src.operators.fitting import fit_operator
from src.operators.group_tests import (
    composition_error,
    identity_error,
    inverse_error,
    s3_relation_errors,
)
import torch


# --- S_3 representation construction ---

def s3_standard_2d_rep() -> dict[Permutation, np.ndarray]:
    """Return the standard 2D irrep matrices for S_3.

    s = (0,1) → reflection, r = (0,1,2) → 120° rotation.
    All 6 elements generated by composition.
    """
    # Standard 2D irrep of S_3
    # s = (0,1): reflection across x-axis
    W_s = np.array([[1.0, 0.0],
                     [0.0, -1.0]])
    # r = (0,1,2): 120° rotation
    c, s_val = np.cos(2 * np.pi / 3), np.sin(2 * np.pi / 3)
    W_r = np.array([[c, -s_val],
                     [s_val, c]])

    group = PermutationGroup(3)
    gens = group.generators()
    s_perm = gens["s"]  # (0,1)
    r_perm = gens["r"]  # (0,1,2)

    # Build all 6 elements
    reps = {}
    reps[Permutation.identity(3)] = np.eye(2)
    reps[s_perm] = W_s
    reps[r_perm] = W_r
    reps[r_perm * r_perm] = W_r @ W_r                    # (0,2,1)
    reps[s_perm * r_perm] = W_s @ W_r                    # (0,2)
    reps[r_perm * s_perm] = W_r @ W_s                    # (1,2)

    # Verify: check all products
    for p1 in group.elements:
        for p2 in group.elements:
            composed = p1 * p2
            if p1 in reps and p2 in reps and composed in reps:
                err = np.linalg.norm(reps[p1] @ reps[p2] - reps[composed])
                assert err < 1e-10, f"Composition {p1}*{p2} error: {err}"

    return reps


def s3_sign_rep() -> dict[Permutation, np.ndarray]:
    """Return the sign (alternating) representation of S_3.

    Even permutations → [1], odd permutations → [-1].
    """
    group = PermutationGroup(3)
    reps = {}
    for perm in group.elements:
        reps[perm] = np.array([[1.0 if perm.is_even else -1.0]])
    return reps


def embed_representation(
    reps: dict[Permutation, np.ndarray],
    d_total: int,
    rng: np.random.Generator,
) -> dict[Permutation, np.ndarray]:
    """Embed a low-dimensional representation into d_total space via random rotation.

    For each permutation π with k×k representation matrix R_π, constructs
    W_π = Q @ diag(R_π, I_{d-k}) @ Q^T

    where Q is a random orthogonal matrix. This places exact group structure
    in a random k-dimensional subspace of R^d_total.
    """
    k = next(iter(reps.values())).shape[0]
    assert k <= d_total

    # Random orthogonal change-of-basis
    Q = ortho_group.rvs(d_total, random_state=rng)

    embedded = {}
    for perm, R in reps.items():
        # Block diagonal: R in top-left, identity elsewhere
        W_block = block_diag(R, np.eye(d_total - k))
        # Rotate into random subspace
        embedded[perm] = Q @ W_block @ Q.T

    return embedded


def make_combined_rep(d_total: int, rng: np.random.Generator) -> dict[Permutation, np.ndarray]:
    """Combine standard 2D irrep + sign rep + trivial rep, embedded in d_total dims.

    This gives a 4-dimensional representation (2+1+1) containing all three
    irreps of S_3, embedded in a random subspace of R^d_total.
    """
    std_2d = s3_standard_2d_rep()
    sign = s3_sign_rep()

    group = PermutationGroup(3)

    # Build 4×4 block-diagonal rep: [standard_2d | sign | trivial]
    combined = {}
    for perm in group.elements:
        R_std = std_2d[perm]      # 2×2
        R_sign = sign[perm]       # 1×1
        R_triv = np.array([[1.0]])  # 1×1
        combined[perm] = block_diag(R_std, R_sign, R_triv)

    return embed_representation(combined, d_total, rng)


def generate_synthetic_data(
    W_dict: dict[Permutation, np.ndarray],
    n_samples: int,
    noise_std: float,
    rng: np.random.Generator,
    effective_dim: int | None = None,
) -> dict[Permutation, tuple[np.ndarray, np.ndarray]]:
    """Generate (base, permuted) activation pairs with exact W_π + Gaussian noise.

    Args:
        W_dict: Permutation -> operator matrix.
        n_samples: Number of samples per permutation.
        noise_std: Standard deviation of additive Gaussian noise.
        effective_dim: If set, base activations live in a random subspace of
            this dimension (simulating a low-rank activation manifold, as in
            real neural networks). If None, activations are full-rank Gaussian.

    Returns dict: permutation -> (X_base, X_permuted) where
        X_permuted = X_base @ W_π.T + noise
    """
    d = next(iter(W_dict.values())).shape[0]

    if effective_dim is not None and effective_dim < d:
        # Generate in a low-dimensional subspace to simulate realistic
        # activation manifolds where n_samples < d_model but the effective
        # rank is low enough for least-squares to work
        Z = rng.standard_normal((n_samples, effective_dim))
        # Random projection into d-dimensional space
        P = rng.standard_normal((effective_dim, d)) / np.sqrt(effective_dim)
        X_base = Z @ P
    else:
        X_base = rng.standard_normal((n_samples, d)).astype(np.float64)

    pairs = {}
    for perm, W in W_dict.items():
        if perm.is_identity:
            continue
        noise = noise_std * rng.standard_normal((n_samples, d))
        X_perm = (W @ X_base.T).T + noise
        pairs[perm] = (X_base, X_perm)

    return pairs


def run_positive_control(
    d_model: int,
    n_samples: int,
    noise_levels: list[float],
    rep_type: str = "combined",
    effective_dim: int | None = None,
    seed: int = 42,
) -> dict:
    """Run the full positive control experiment.

    For each noise level:
    1. Generate synthetic activations with exact S_3 structure
    2. Fit operators via least-squares (same as real pipeline)
    3. Test group relations
    4. Report errors

    Args:
        effective_dim: If set, base activations live in a random subspace of
            this dimension. This simulates realistic neural activations where
            the effective rank is much lower than d_model.
    """
    rng = np.random.default_rng(seed)
    group = PermutationGroup(3)
    gens = group.generators()
    s_perm = gens["s"]
    r_perm = gens["r"]

    # Build exact representation
    if rep_type == "combined":
        W_exact = make_combined_rep(d_model, rng)
        rep_dim = 4
    elif rep_type == "standard_2d":
        W_exact = embed_representation(s3_standard_2d_rep(), d_model, rng)
        rep_dim = 2
    elif rep_type == "sign":
        W_exact = embed_representation(s3_sign_rep(), d_model, rng)
        rep_dim = 1
    else:
        raise ValueError(f"Unknown rep_type: {rep_type}")

    # Verify exact operators satisfy group relations perfectly
    W_s_exact = W_exact[s_perm]
    W_r_exact = W_exact[r_perm]
    exact_rels = s3_relation_errors(W_s_exact, W_r_exact)
    print(f"\nExact operator relation errors (should be ~0):")
    for name, err in exact_rels.items():
        print(f"  {name}: {err.relative_error:.2e}")

    results = {}

    for noise_std in noise_levels:
        eff_str = f", eff_dim={effective_dim}" if effective_dim else ""
        print(f"\n{'='*70}")
        print(f"Noise σ = {noise_std:.4f} (rep_type={rep_type}, dim={rep_dim}, "
              f"d_model={d_model}, n_samples={n_samples}{eff_str})")
        print(f"{'='*70}")

        # Generate data
        pairs = generate_synthetic_data(W_exact, n_samples, noise_std, rng,
                                        effective_dim=effective_dim)

        # Fit operators (same pipeline as real experiment)
        fitted_ops = {}
        fit_info = {}
        fitted_ops[Permutation.identity(3)] = np.eye(d_model)

        for perm, (X_base, X_perm) in pairs.items():
            fit = fit_operator(
                torch.tensor(X_base, dtype=torch.float64),
                torch.tensor(X_perm, dtype=torch.float64),
            )
            fitted_ops[perm] = fit.W
            fit_info[perm] = {
                "train_error": fit.relative_error,
                "test_error": fit.test_relative_error,
                "test_cosine": fit.test_cosine_similarity,
                "parity": perm.parity,
            }

        # Report fit quality
        print(f"\nOperator fit quality:")
        for perm, info in fit_info.items():
            parity_str = "even" if info["parity"] == 0 else "odd"
            print(f"  {str(perm):>15s} ({parity_str}): "
                  f"test_err={info['test_error']:.6f}, "
                  f"test_cos={info['test_cosine']:.6f}")

        # Test group relations
        W_s = fitted_ops[s_perm]
        W_r = fitted_ops[r_perm]
        s3_rels = s3_relation_errors(W_s, W_r)

        print(f"\nS_3 presentation relations:")
        for name, err in s3_rels.items():
            print(f"  {name}: relative_error = {err.relative_error:.6f}")

        # Inverse errors
        inv_errors = {}
        for perm in fitted_ops:
            if perm.is_identity:
                continue
            perm_inv = perm.inverse()
            if perm_inv in fitted_ops:
                inv_err = inverse_error(fitted_ops[perm], fitted_ops[perm_inv])
                inv_errors[str(perm)] = inv_err.relative_error

        mean_inv = float(np.mean(list(inv_errors.values()))) if inv_errors else None
        print(f"  Mean inverse error: {mean_inv:.6f}")

        # Composition errors
        comp_errors = []
        for p1 in group.elements:
            for p2 in group.elements:
                if p1.is_identity or p2.is_identity:
                    continue
                composed = p1 * p2
                if composed in fitted_ops and p1 in fitted_ops and p2 in fitted_ops:
                    err = composition_error(fitted_ops[p1], fitted_ops[p2], fitted_ops[composed])
                    comp_errors.append(err.relative_error)

        mean_comp = float(np.mean(comp_errors)) if comp_errors else None
        print(f"  Mean composition error: {mean_comp:.6f}")

        results[noise_std] = {
            "noise_std": noise_std,
            "rep_type": rep_type,
            "rep_dim": rep_dim,
            "d_model": d_model,
            "n_samples": n_samples,
            "fit_quality": {str(p): v for p, v in fit_info.items()},
            "s3_relations": {
                name: {"frobenius": r.frobenius_error, "relative": r.relative_error}
                for name, r in s3_rels.items()
            },
            "mean_inverse_error": mean_inv,
            "mean_composition_error": mean_comp,
        }

    return results


def main():
    parser = argparse.ArgumentParser(description="Positive control: synthetic S_3 group structure")
    parser.add_argument("--noise-levels", type=float, nargs="+",
                        default=[0.0, 0.01, 0.05, 0.1, 0.2, 0.5, 1.0],
                        help="Gaussian noise standard deviations")
    parser.add_argument("--output", type=str, default=None)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    all_results = {}

    # --- Scenario 1: Clean proof of concept ---
    # Small d where n >> d, so least-squares is well-conditioned
    print(f"\n{'#'*70}")
    print(f"# SCENARIO 1: Clean proof (d=10, n=200)")
    print(f"# Pipeline detects exact group structure when system is well-posed")
    print(f"{'#'*70}")
    results = run_positive_control(
        d_model=10, n_samples=200,
        noise_levels=args.noise_levels,
        rep_type="combined", seed=args.seed,
    )
    all_results["clean_d10"] = results

    # --- Scenario 2: Realistic d, low-rank activations ---
    # d=896 matching real model, but activations on a ~50-dim manifold
    # (realistic: real neural activations are low-rank)
    print(f"\n{'#'*70}")
    print(f"# SCENARIO 2: Realistic scale (d=896, n=100, eff_dim=50)")
    print(f"# Group structure in 896-dim space, activations on 50-dim manifold")
    print(f"{'#'*70}")
    results = run_positive_control(
        d_model=896, n_samples=100,
        noise_levels=args.noise_levels,
        rep_type="combined", effective_dim=50, seed=args.seed,
    )
    all_results["realistic_eff50"] = results

    # --- Scenario 3: Realistic d, higher-rank activations ---
    print(f"\n{'#'*70}")
    print(f"# SCENARIO 3: Higher rank (d=896, n=100, eff_dim=80)")
    print(f"{'#'*70}")
    results = run_positive_control(
        d_model=896, n_samples=100,
        noise_levels=args.noise_levels,
        rep_type="combined", effective_dim=80, seed=args.seed,
    )
    all_results["realistic_eff80"] = results

    # --- Summary ---
    print(f"\n\n{'='*95}")
    print(f"SUMMARY: Positive Control vs Real Model")
    print(f"{'='*95}")
    print(f"\n{'Scenario':>18s}  {'Noise':>7s}  {'TestErr':>8s}  "
          f"{'s²=e':>8s}  {'r³=e':>8s}  {'srs':>8s}  "
          f"{'Inv':>8s}  {'Comp':>8s}")
    print("─" * 95)

    for scenario, results in all_results.items():
        for noise_std, r in results.items():
            test_errs = [v["test_error"] for v in r["fit_quality"].values()
                         if v["test_error"] is not None]
            mean_test = float(np.mean(test_errs)) if test_errs else float("nan")
            s3 = r["s3_relations"]
            print(f"{scenario:>18s}  {noise_std:>7.3f}  {mean_test:>8.6f}  "
                  f"{s3['s^2 = e']['relative']:>8.6f}  "
                  f"{s3['r^3 = e']['relative']:>8.6f}  "
                  f"{s3['srs = r^{-1}']['relative']:>8.6f}  "
                  f"{r['mean_inverse_error']:>8.6f}  "
                  f"{r['mean_composition_error']:>8.6f}")

    # Print real model results for comparison
    print(f"\n{'--- Real Model (Qwen2.5-0.5B) for comparison ---':>95s}")
    print(f"{'Layer 0':>18s}  {'─':>7s}  {'0.0775':>8s}  "
          f"{'1.0229':>8s}  {'1.0936':>8s}  {'0.5227':>8s}  "
          f"{'1.0494':>8s}  {'1.0786':>8s}")
    print(f"{'Layer 21':>18s}  {'─':>7s}  {'0.2577':>8s}  "
          f"{'1.0149':>8s}  {'1.0237':>8s}  {'0.7420':>8s}  "
          f"{'1.0157':>8s}  {'0.9838':>8s}")
    print(f"\nKey: Real model has LOW test error (good operator fit) but HIGH")
    print(f"relation errors (~1.0). Positive control shows that when group")
    print(f"structure IS present, relation errors stay low even with noise.")

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        def ser(obj):
            if isinstance(obj, (np.floating, np.integer)):
                return float(obj)
            raise TypeError(f"Not serializable: {type(obj)}")

        save = {k: {str(kk): vv for kk, vv in v.items()} for k, v in all_results.items()}
        output_path.write_text(json.dumps(save, indent=2, default=ser))
        print(f"\nResults saved to {output_path}")


if __name__ == "__main__":
    main()
